### ISSUE TITLE
[BUG] start.sh error: Additional property content is not allowed

### ISSUE THREAD

**Issue by shubham78901** [bitcoin-sv/spv-wallet#550]
getting this error when starting  after "./start.sh"
error=validating D:\Desktop\spv-wallet\docker-compose.yml: configs.frontend-env-config Additional property content is not allowed

**Comment by Klar** [comment]
I get the same error, did you find a solution?

**Comment by shubham78901** [comment]
No,

**Comment by dorzepowski** [comment]
I'm sorry for a late answer.
It seems that you both have old version of docker compose,
1. can you check if you have `docker compose` command or only `docker-compose` command is available?
2. can you check the version of docker compose?

**Comment by dorzepowski** [comment]
Closing the issue because of no followup questions for over a month.
