### ISSUE TITLE
[BUG] no instructions on how to expose a public domain from the quickstart

### ISSUE THREAD

**Issue by petermchale** [bitcoin-sv/spv-wallet#575]
**TL;DR**
Check if your issue answers those question:

- [x]  Does my issue clearly describe what exactly is not working properly?
- [X]  Does my issue clearly describe what are my expectations and what is the current output?
- [X]  Did I attach logs/screenshots/errors which ocured?
- [X]  Did I provide information how I run the code/library/application and on which platform/browser?

**Describe the bug**
Cannot make a transaction to the wallet from the Quickstart. 

**To Reproduce**
1. Follow the steps in the quickstart: https://docs.bsvblockchain.org/installation/quickstart
2. When you get to the last step (https://docs.bsvblockchain.org/installation/quickstart#how-can-i-make-a-transaction-to-the-wallet), you realize you need to "expose a public domain", but the link provided is stale (https://github.com/bitcoin-sv/gitbook-spv-wallet/blob/master/get-started/broken-reference/README.md)

**Expected behavior**
There should be clear instructions on how to expose a public domain at this point in the quickstart; otherwise a new user cannot test the software quickly. 

**Logs**
n/a

**Screenshots**
n/a

**Used environment (please complete the following information):**
n/a

**Additional context**

**Comment by dorzepowski** [comment]
I'm sorry for a late answer.
It seems that you both have old version of docker compose,
1. can you check if you have `docker compose` command or only `docker-compose` command is available?
2. can you check the version of docker compose?

**Comment by dorzepowski** [comment]
Sorry for late answer:
the link should be already fixed. But the instruction (target of the link) was already there on the same page:
https://docs.bsvblockchain.org/installation/quickstart#exposing-on-public-domains
if this is not enough, feel free to ask the questions so we can understand what should be clarified.
