### ISSUE TITLE
What is the role of externalXpubKeyNum, pubKeyNum, xpubDerivationSeq, and how are they useful in paymailAddress ?

### ISSUE THREAD

**Issue by nikhil478** [bitcoin-sv/spv-wallet#651]
I would really appreciate any help on this :)

**Comment by dorzepowski** [comment]
Context:
1. spv-wallet doesn't store the xpub itself
2. spv-wallet stores derived xpub key for paymail
3. spv-wallet is still using bip32 derivation schema

Answer:
1. **externalXpubKeyNum** - is used to derive and store xpub used for paymail operations, in other words`paymailExternalXpub => m/0/externalXpubKeyNum`
2. **pubKeyNum** - is used to derive a key from `paymailExternalXpub` for PKI paymail capability 
4. **xpubDerivationSeq** - is used to derive a key from `paymailExternalXpub` for locking script returned in paymail destination capability
