### ISSUE TITLE
[FEATURE] Documentation for configuring paymail domain / dns

### ISSUE THREAD

**Issue by Klar** [bitcoin-sv/spv-wallet#796]
## Desired Solution
Can someone point me to the documentation on how to create DNS for paymail, what is needed?

I'm unable to find it in the documentation / quickstart guide.

**Comment by proapi** [comment]
There is no need for any specific configuration, you need to point the domain on which you want to configure the paymail working to the IP that spv-wallet is running. In most cases it is an A record in your DNS zone configuration. In spv-wallet config you need to specify this domain, and that is it.
